/**
 * THIS FILE IS AUTO-GENERATED BY build-features.mjs
 * DO NOT EDIT MANUALLY - Your changes will be overwritten
 *
 * To add a new feature:
 * 1. Create a new directory in dev/src/features/
 * 2. Add an index.ts file with a create function and type export
 * 3. Run: bun run build
 *
 * Generated on: 2026-01-09T14:18:56.662Z
 */

import * as exampleFeatureModule from "./example-feature";
import * as multitoolModule from "./multitool";

/**
 * Array of all discovered features with their metadata
 */
export const features = [
  { name: "exampleFeature", create: exampleFeatureModule.createExampleFeature },
  { name: "multitool", create: multitoolModule.createMultitool },
] as const;

/**
 * Union type of all feature instances
 */
export type Feature = ReturnType<typeof exampleFeatureModule.createExampleFeature> | ReturnType<typeof multitoolModule.createMultitool>;
