/**
 * THIS FILE IS AUTO-GENERATED BY build-plugins.mjs
 * DO NOT EDIT MANUALLY - Your changes will be overwritten
 *
 * To add a new plugin:
 * 1. Create a new directory in src/plugins/
 * 2. Add an index.ts file with a create function and type export
 * 3. Run: bun run build
 *
 * Generated on: 2026-01-31T11:21:37.470Z
 */

import * as debugModule from "./debug";
import * as examplePluginModule from "./example-plugin";

/**
 * Array of all discovered plugins with their metadata
 */
export const plugins = [
  { name: "debug", create: debugModule.createDebug },
  { name: "examplePlugin", create: examplePluginModule.createExamplePlugin },
] as const;

/**
 * Union type of all plugin instances
 */
export type Plugin = ReturnType<typeof debugModule.createDebug> | ReturnType<typeof examplePluginModule.createExamplePlugin>;
